[window]
decorations = "transparent"
dynamic_padding = true

[window.padding]
x = 20
y = 35

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

[keyboard]
bindings = [
  { key = "C", mods = "Super", action = "Copy" },
  { key = "V", mods = "Super", action = "Paste" }
]
